Added: [G6-23]: Create function multiplication table - exercise 11
desenvolve06/gr6-projeto1 pull request #16
Opened 2024-03-17 23:40 UTC by arlannunesdev

Esta função gera um número aleatório e calcula a sua tabuada. A classe Random é usada para gerar um número aleatório entre 0 e 9. A funçao showMultiplicationTable é chamada, gerando um número aleatório, calculando sua tabuada e exibindo os resultados na tela:
**Screenrecord**
 
[Video Challenge 11.webm](https://github.com/desenvolve06/gr6-projeto1/assets/162641327/d1cd490f-d223-46f7-9540-74567d532904)

Tarefa Trello
[G6-23](https://trello.com/c/XSkjMhah/23-g6-23-desafio-11-create-exercise-11)

2024-03-17 23:47 UTC, mauriciomuniz approved these changes

2024-03-18 00:01 UTC, mauriciomuniz requested changes
resolver conflitos

2024-03-18 00:10 UTC, CarlosEduardo31 approved these changes

2024-03-18 00:31 UTC, LucianaCabral approved these changes

2024-03-18 00:33 UTC, arlannunesdev reviewed
Conflitos resolvidos!

2024-03-18 00:34 UTC, mauriciomuniz approved these changes

2024-03-18 00:37 UTC, merged